### ISSUE TITLE
Book appointment options

### ISSUE THREAD

**Issue by IonRutz** [MachoThemes/regina-lite#18]
Acum lipsesc optiunile pt butonul de book appointment din menu.
![image](https://cloud.githubusercontent.com/assets/15014267/17533679/980aea84-5e8e-11e6-88c4-92b570e14e22.png)

Acum se poate schimba doar linkul in contact details.

Ar fi ok sa fie in primul rand posibilitatea de disable, apoi sa se poate modifica textul butonului.

Thx

**Comment by cristianraiber** [comment]
@IonRutz - se poate sterge "#" si atunci dispare butonul de book appointment. O functionalitate suplimentara mi s-ar parea redundanta.
