### ISSUE TITLE
Default widget styling

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/regina-lite#22]
1. Spacing between elements

--- 

![screen shot 2016-08-17 at 13 02 17](https://cloud.githubusercontent.com/assets/7841556/17732521/daa16782-647a-11e6-8d3d-ee04b300086d.png)

**Comment by IonRutz** [comment]
Calendar days alignment issue:
![image](https://cloud.githubusercontent.com/assets/15014267/17892287/3265eb6e-6949-11e6-87a4-6df4023d9127.png)
