### ISSUE TITLE
Top bar Go search button not aligned

### ISSUE THREAD

**Issue by IonRutz** [MachoThemes/regina-lite#32]
![image](https://cloud.githubusercontent.com/assets/15014267/17892681/386ec27c-694b-11e6-879a-0ecfe7e56711.png)

Are o mica deplasare in jos.
Pe live demo apare in regula, deci  ma gandesc ca a aparut problema recent.

Browser Chrome.

**Comment by cristianraiber** [comment]
Looks fine in Chrome/Safari/Firefox.
